2020-10-21 20:15:10,472 INFO    MainThread:20705 [wandb_init.py:_log_setup():292] Logging user logs to wandb/run-20201021_201510-2opa4kwr/logs/debug.log
2020-10-21 20:15:10,472 INFO    MainThread:20705 [wandb_init.py:_log_setup():293] Logging internal logs to wandb/run-20201021_201510-2opa4kwr/logs/debug-internal.log
2020-10-21 20:15:10,472 INFO    MainThread:20705 [wandb_setup.py:_flush():69] setting env: {}
2020-10-21 20:15:10,472 INFO    MainThread:20705 [wandb_setup.py:_flush():69] setting user settings: {'save_code': False, 'email': 'chinmay.srao97@gmail.com'}
2020-10-21 20:15:10,472 INFO    MainThread:20705 [wandb_setup.py:_flush():69] multiprocessing start_methods=fork,spawn,forkserver
2020-10-21 20:15:11,890 WARNING MainThread:20705 [wandb_init.py:init():483] interrupted
Traceback (most recent call last):
  File "/home/zk315372/Chinmay/maastro_env/lib64/python3.6/site-packages/wandb/sdk/wandb_init.py", line 463, in init
    run = wi.init()
  File "/home/zk315372/Chinmay/maastro_env/lib64/python3.6/site-packages/wandb/sdk/wandb_init.py", line 369, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/zk315372/Chinmay/maastro_env/lib64/python3.6/site-packages/wandb/interface/interface.py", line 533, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/zk315372/Chinmay/maastro_env/lib64/python3.6/site-packages/wandb/interface/interface.py", line 524, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/zk315372/Chinmay/maastro_env/lib64/python3.6/site-packages/wandb/interface/interface.py", line 437, in _communicate
    return future.get(timeout)
  File "/home/zk315372/Chinmay/maastro_env/lib64/python3.6/site-packages/wandb/interface/interface.py", line 58, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib64/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib64/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2020-10-21 20:15:11,898 INFO    MainThread:20705 [internal.py:handle_exit():137] Internal process exited
